---
name: Lint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.x"
      - run: python3 --version

      - run: |
          python3 -m pip install --upgrade pip
          pip3 --version

      - run: |
          pip3 install gitlint
          gitlint --version
          gitlint --ignore body-is-missing -c title-max-length.line-length=50

      - run: if git ls-files | xargs file | grep CRLF; then exit 1; fi
